### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by markdorison** [adam7/platformsh-cli-action#10]
When I attempt to use this action, I see the following error:

```yaml
- uses: actions/checkout@v2
- uses: adam7/platformsh-cli-action@v1.0
  with:
    token: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
```

```
Error: Cannot find module '@actions/core'
```

![image](https://user-images.githubusercontent.com/20355/108264476-94e25b80-7135-11eb-940d-343fcd046f0e.png)

After doing some initial research, it seems like this is related to the [`node_modules` directory not being committed](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github). It looks like it is committed on the [`releases/v1` branch](https://github.com/adam7/platformsh-cli-action/tree/releases/v1) but not in the tagged release which is what I am pointing to.
