### ISSUE TITLE
Repository not found error when using in GitHub actions 

### ISSUE THREAD

**Issue by SavitaMaurya** [adam7/platformsh-cli-action#8]
Hey Adam,

I wanted to install Platformsh CLI in Github workflow and got to know about you repo.

I tried the way mentioned in Readme but unsuccessful. Please suggest and if possible tag somebody who have used your repo in their workflow. Thanks :)

![Screenshot 2020-11-05 at 13 27 03](https://user-images.githubusercontent.com/47749634/98241257-fc9bde80-1f6a-11eb-9f9c-6415d6620c87.png)
![Screenshot 2020-11-05 at 13 27 18](https://user-images.githubusercontent.com/47749634/98241266-fdcd0b80-1f6a-11eb-8f03-2fc43879669b.png)

**Comment by adam7** [comment]
Hey @SavitaMaurya 

Looks like I didn't update the repository name in the readme when I moved itI've fixed that now. Can you test with this code and let me know if it works
```
- uses: actions/checkout@v1
- uses: adam7/platformsh-cli-action@v1
  with: 
    token: ${{secrets.PLATFORMSH_CLI_TOKEN}} #required
```
