### ISSUE TITLE
Failed to resolve action download info

### ISSUE THREAD

**Issue by markdorison** [adam7/platformsh-cli-action#9]
I am getting the following error when attempting to use the action as described in the README:

```yaml
- uses: actions/checkout@v2
- uses: adam7/platformsh-cli-action@v1
  with:
    token: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
```

```
Failed to resolve action download info. Error: Unable to resolve action `adam7/platformsh-cli-action@v1`, unable to find version `v1`
```

<img width="850" alt="image" src="https://user-images.githubusercontent.com/20355/107964526-628aff80-6f77-11eb-84be-6959d51490e3.png">

I thought it might be related to a version/tag so I tried specifying the branch name `@master` but that failed as well.
